apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: name-virtual-ingress
  namespace: default
spec:
  rules:
  - host: foo.bar.com
  - http:
      paths:
      - path: /
        backend:
          serviceName: nginx
          servicePort: 80